name: tf
channels:
  - conda-forge
  - defaults
dependencies:
  - boost=1.68.0
  - boost-cpp=1.68.0
  - bzip2=1.0.6
  - icu=58.2
  - blas=1.0
  - ca-certificates=2018.03.07
  - certifi=2018.8.24
  - cycler=0.10.0
  - freetype=2.9.1
  - intel-openmp=2019.0
  - kiwisolver=1.0.1
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libopenblas=0.2.20
  - libpng=1.6.34
  - matplotlib=3.0.0
  - mkl=2019.0
  - mkl_fft=1.0.6
  - mkl_random=1.0.1
  - ncurses=6.1
  - numpy=1.15.2
  - numpy-base=1.15.2
  - openssl=1.0.2p
  - pip=10.0.1
  - pyparsing=2.2.0
  - python=3.6.6
  - python-dateutil=2.7.3
  - pytz=2018.5
  - readline=7.0
  - setuptools=40.0.0
  - six=1.11.0
  - sqlite=3.24.0
  - tk=8.6.7
  - tornado=5.1
  - wheel=0.31.1
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - absl-py==0.4.0
    - ad3==2.2.1
    - apipkg==1.5
    - appnope==0.1.0
    - astor==0.7.1
    - atomicwrites==1.2.1
    - attrs==18.2.0
    - backcall==0.1.0
    - bleach==1.5.0
    - click==6.7
    - configparser==3.5.0
    - cython==0.29
    - decorator==4.3.0
    - defusedxml==0.5.0
    - deprecated==1.2.1
    - dicom2nifti==2.0.3
    - entrypoints==0.2.3
    - et-xmlfile==1.0.1
    - execnet==1.5.0
    - flask==1.0.2
    - funcsigs==1.0.2
    - future==0.16.0
    - gast==0.2.0
    - graphviz==0.9
    - grpcio==1.14.1
    - h5py==2.8.0
    - html5lib==0.9999999
    - ipykernel==5.1.0
    - ipython==7.0.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.4.2
    - isodate==0.6.0
    - itsdangerous==1.1.0
    - jdcal==1.4
    - jedi==0.13.1
    - jinja2==2.10
    - jsonschema==2.6.0
    - jupyter==1.0.0
    - jupyter-client==5.2.3
    - jupyter-console==6.0.0
    - jupyter-core==4.4.0
    - keras==2.1.6
    - lxml==4.2.5
    - markdown==2.6.11
    - markupsafe==1.0
    - medpy==0.4.0
    - mistune==0.8.4
    - mock==2.0.0
    - more-itertools==4.3.0
    - mpmath==1.0.0
    - natsort==5.3.3
    - nbconvert==5.4.0
    - nbformat==4.4.0
    - networkx==2.1
    - nibabel==2.3.0
    - nipy==0.4.2
    - nipype==1.1.2
    - nltk==3.4
    - notebook==5.7.0
    - opencv-python==3.4.2.17
    - openpyxl==2.5.8
    - packaging==17.1
    - pandas==0.23.4
    - pandocfilters==1.4.2
    - parso==0.3.1
    - patsy==0.5.1
    - pbr==4.2.0
    - pexpect==4.6.0
    - pickleshare==0.7.5
    - pillow==5.2.0
    - pluggy==0.7.1
    - prometheus-client==0.4.2
    - prompt-toolkit==2.0.6
    - protobuf==3.6.1
    - prov==1.5.0
    - psutil==5.4.7
    - ptyprocess==0.6.0
    - py==1.6.0
    - pydensecrf==1.0rc3
    - pydicom==1.1.0
    - pydot==1.2.4
    - pydotplus==2.0.2
    - pygments==2.2.0
    - pypng==0.0.19
    - pystruct==0.3.2
    - pytest==3.8.0
    - pytest-forked==0.2
    - pytest-xdist==1.23.0
    - pywavelets==0.5.2
    - pyyaml==3.13
    - pyzmq==17.1.2
    - qtconsole==4.4.2
    - rdflib==4.2.2
    - resnet==0.1
    - scikit-image==0.13.1
    - scikit-posthocs==0.4.0
    - scipy==1.1.0
    - seaborn==0.9.0
    - send2trash==1.5.0
    - simplegeneric==0.8.1
    - simpleitk==1.1.0
    - simplejson==3.16.0
    - singledispatch==3.4.0.3
    - statsmodels==0.9.0
    - sympy==1.3
    - tensorboard==1.8.0
    - tensorflow==1.8.0
    - termcolor==1.1.0
    - terminado==0.8.1
    - testpath==0.4.2
    - traitlets==4.3.2
    - traits==4.6.0
    - wcwidth==0.1.7
    - werkzeug==0.14.1
    - widgetsnbextension==3.4.2
    - wrapt==1.10.11
    - xlrd==1.1.0

